title: rpi-mp3-player
hero_image: images/banner.png
description: rpi-mp3-player description
version: 4
listed: false
copyedit: false
last_tested: "2019-08-13"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
